### PR TITLE
Update for the FRENCH translation for Add user extension

### PR DESCRIPTION
**Pull request by Galixte**
Update for FRENCH translation for info_acp_adduser.php file
FRENCH translation for user_added_admin_welcome_inactive.txt file
FRENCH translation for user_added_inactive.txt file
FRENCH translation for user_added_welcome.txt file

### CODE REVIEW

**Comment by Galixte** [comment]
I don't see the next string in ACP page of this extension :

```
'GROUP_DEFAULT_EXPLAIN'
```

**Comment by Galixte** [comment]
HI,

Everything is OK about my previous message ;=)

**Comment by Galixte** [comment]
Well, it's OK for me :=)

**Comment by Galixte** [comment]
Hi,

it's OK for you ?

**Comment by tumba25** [comment]
thanks

**Pull request merged**
